name: Validar Quiz Desafios Trabalho em Equipe com Multiplas Versoes
on:
  push:
    paths: 
      - '.github/workflows/quiz_validation_Desafios_Equipe_Multiplas_Versoes.yml'

permissions:
  write-all

jobs:
  validar_quiz:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Obter conteúdo da issue
        id: obter_issue
        uses: actions/github-script@v6
        with:
          script: |
            const issueTitulo = "Desafio Quiz: Desafios do Trabalho em Equipe com Múltiplas Versões";
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'all',
            });

            const issue = issues.data.find(i => i.title === issueTitulo);

            if (!issue) {
              console.log(`Issue "${issueTitulo}" não encontrada.`);
              return;
            }

            core.setOutput('issueNumber', issue.number);
            return issue.body;

      - name: Validar respostas do quiz
        id: validar_respostas
        uses: actions/github-script@v6
        with:
          script: |
            const issueBody = ${{ steps.obter_issue.outputs.result }};
            if (!issueBody) return;

            const respostasCorretas = {
              "1": "Quanto mais tempo e extensivamente os ramos divergem do tronco principal, maior a probabilidade de alterações conflitantes.",
              "2": "Divergências significativas na forma como diferentes colaboradores modificaram a mesma parte do projeto.",
              "3": "Não sincronizar regularmente sua cópia local do projeto com o repositório central antes de enviar suas alterações.",
              "4": "Dificulta a compreensão do trabalho dos outros, aumentando a probabilidade de conflitos e decisões desinformadas durante a resolução.",
              "5": "Dificulta a compreensão da origem das alterações e o contexto dos conflitos, tornando a resolução mais complexa.",
              "6": "Geração de um volume massivo de conflitos interconectados, tornando a integração complexa e arriscada.",
              "7": "Diferentes fluxos de trabalho estabelecem diferentes práticas de integração, impactando a frequência e a complexidade dos conflitos.",
              "8": "Ação de trazer as últimas atualizações da versão central para a sua versão local."
            };

            const respostasUsuario = {};
            const perguntas = issueBody.split("# ");

            perguntas.slice(1).forEach(pergunta => {
              const numeroPergunta = pergunta.split(" - ")[0];
              const opcoes = pergunta.split("- [");

              opcoes.slice(1).forEach(opcao => {
                if (opcao.startsWith("x")) {
                  respostasUsuario[numeroPergunta] = opcao.split("] ")[1].trim();
                }
              });
            });

            let feedback = "## Resultado do Quiz\n\n";
            let todasCorretas = true;

            function sanitizeString(str) {
              return str.normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[\u200B-\u200F\uFEFF]/g, '').trim().replace(/^"(.*)"$/, '$1');
            }

            for (const numeroPergunta in respostasCorretas) {
              const respostaCorreta = sanitizeString(respostasCorretas[numeroPergunta]);
              const respostaUsuario = respostasUsuario[numeroPergunta] ? sanitizeString(respostasUsuario[numeroPergunta]) : "";

              if (respostaUsuario === respostaCorreta) {
                feedback += `✅ Pergunta ${numeroPergunta}: Resposta correta!\n`;
              } else {
                feedback += `❌ Pergunta ${numeroPergunta}: Resposta incorreta. Resposta correta: ${respostasCorretas[numeroPergunta]}\n`;
                todasCorretas = false;
              }
            }

            if (todasCorretas) {
              feedback += "\nParabéns! Você acertou todas as perguntas do quiz.";
            } else {
              feedback += "\nPor favor, revise suas respostas e tente novamente.";
            }

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ steps.obter_issue.outputs.issueNumber }},
              body: feedback,
            });
