name: Validar Quiz Organizacao e Estrutura do Repositorio
on:
  workflow_dispatch:
    inputs: # Esta seção 'inputs' é necessária se você estiver enviando inputs do seu código Java
      content_node_id:
        description: 'The content node ID (Issue ID)'
        required: true
        type: string
      project_id:
        description: 'The project ID'
        required: true
        type: string
      original_card_title:
        description: 'Título original do card do projeto/issue'
        required: true
        type: string
      webhook_payload:
        description: 'Payload completo do webhook em formato string JSON'
        required: true
        type: string

permissions:
  write-all

jobs:
  validar_quiz:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Obter conteúdo da issue
        id: obter_issue
        uses: actions/github-script@v6
        with:
          script: |
            // O log do payload completo para depuração
            console.log('context.payload:', JSON.stringify(context.payload, null, 2));

            // A linha corrigida para acessar o issueTitulo
            const issueTitulo = context.payload.inputs.original_card_title;
            
            console.log(`Buscando issue com o título: "${issueTitulo}"`);
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'all',
            });

            const issue = issues.data.find(i => i.title === issueTitulo);

            if (!issue) {
              console.log(`Issue "${issueTitulo}" não encontrada.`);
              return;
            }

            core.setOutput('issueNumber', issue.number);
            return issue.body;

      - name: Validar respostas do quiz
        id: validar_respostas
        uses: actions/github-script@v6
        with:
          script: |
            const issueBody = ${{ steps.obter_issue.outputs.result }};
            if (!issueBody) return;
            const respostasCorretas = {
              "1": "Facilitar a localização de arquivos e reduzir a curva de aprendizado para entender a estrutura.",
              "2": "Reduz a chance de conflitos e torna a integração do trabalho mais fluida, pois todos sabem onde cada componente deve estar.",
              "3": "Simplifica a adição de novos módulos, a atualização de bibliotecas e a correção de problemas, permitindo que o projeto cresça de forma controlada.",
              "4": "Cada pasta representa uma funcionalidade completa, contendo todos os arquivos relacionados a ela.",
              "5": "Combina o melhor da organização por tipo e por funcionalidade, sendo adequada para projetos de médio a grande porte.",
              "6": "A padronização de nomes e estruturas reduz a confusão e facilita a localização de arquivos por qualquer membro da equipe.",
              "7": "Dificultam a localização de arquivos específicos, geram confusão e tornam a navegação no projeto ineficiente.",
              "8": "Significa manter arquivos de configuração, documentação, recursos estáticos, etc., em locais próprios, para manter o código-fonte limpo e fácil de gerenciar."
            };
            const respostasUsuario = {};
            const perguntas = issueBody.split("### ");
            perguntas.slice(1).forEach(pergunta => {
              const numeroPergunta = pergunta.split(" - ")[0];
              const linhas = pergunta.split('\n');
              for (const linha of linhas) {
                if (linha.startsWith("- [x]")) {
                  const textoOpcao = linha.substring(linha.indexOf("] ") + 2).trim();
                  respostasUsuario[numeroPergunta] = textoOpcao;
                  break;
                }
              }
            });
            let feedback = "## Resultado do Quiz\n\n";
            let todasCorretas = true;
            function sanitizeString(str) {
              return str.normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[\u200B-\u200F\uFEFF]/g, '').trim().replace(/^"(.*)"$/, '$1');
            }
            for (const numeroPergunta in respostasCorretas) {
              const respostaCorreta = sanitizeString(respostasCorretas[numeroPergunta]);
              const respostaUsuario = respostasUsuario[numeroPergunta] ? sanitizeString(respostasUsuario[numeroPergunta]) : "";
              if (respostaUsuario === respostaCorreta) {
                feedback += `✅ Pergunta ${numeroPergunta}: Resposta correta!\n`;
              } else {
                feedback += `❌ Pergunta ${numeroPergunta}: Resposta incorreta. Resposta correta: ${respostasCorretas[numeroPergunta]}\n`;
                todasCorretas = false;
              }
            }
            if (todasCorretas) {
              feedback += "\nParabéns! Você acertou todas as perguntas do quiz.";
            } else {
              feedback += "\nPor favor, revise suas respostas e tente novamente.";
            }
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ steps.obter_issue.outputs.issueNumber }},
              body: feedback,
            });
