name: Validar Quiz Versionamento e a Automação de Processos
on: 
  push:
    paths:
      - '.github/workflows/quiz_validation_versionamento_automacao.yml'

permissions:
  write-all

jobs:
  validar_quiz:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Obter conteúdo da issue
        id: obter_issue
        uses: actions/github-script@v6
        with:
          script: |
            // Título da issue deve corresponder EXATAMENTE ao título do seu quiz
            const issueTitulo = "Desafio Quiz: Versionamento e a Automação de Processos";
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'all',
            });

            const issue = issues.data.find(i => i.title === issueTitulo);

            if (!issue) {
              console.log(`Issue "${issueTitulo}" não encontrada.`);
              return;
            }

            core.setOutput('issueNumber', issue.number);
            return issue.body;

      - name: Validar respostas do quiz
        id: validar_respostas
        uses: actions/github-script@v6
        with:
          script: |
            const issueBody = ${{ steps.obter_issue.outputs.result }};
            if (!issueBody) return;

            // AS RESPOSTAS CORRETAS EXATAS PARA O QUIZ "Versionamento e a Automação de Processos"
            const respostasCorretas = {
              "1": "Ao registrar uma nova alteração no código (uma nova \"versão\" salva), ele sinaliza que algo novo precisa ser processado pela automação.",
              "2": "Garante que as ferramentas de automação sempre trabalhem com a versão exata e consistente do código, removendo ambiguidades.",
              "3": "Garante que a automação esteja sempre trabalhando com a versão mais recente e completa do código disponível.",
              "4": "Permite que problemas de integração ou bugs sejam detectados quase instantaneamente após uma alteração ser registrada e testada automaticamente.",
              "5": "Garante que os \"produtos\" finais do software sejam identificados com base na versão do código, criando um histórico rastreável de cada lançamento.",
              "6": "Permite que a automação retorne o sistema rapidamente para uma versão estável anterior, minimizando o tempo de inatividade.",
              "7": "Para alcançar maior frequência de lançamentos, detecção precoce de problemas, e uma confiança inabalável na qualidade do software."
            };


            const respostasUsuario = {};
            const perguntas = issueBody.split("### ");

            perguntas.slice(1).forEach(pergunta => {
              const numeroPerguntaMatch = pergunta.match(/^(\d+) - /);
              if (!numeroPerguntaMatch) return;

              const numeroPergunta = numeroPerguntaMatch[1];
              const linhasDaPergunta = pergunta.split('\n');

              for (const linha of linhasDaPergunta) {
                if (linha.includes('- [x]')) {
                  const matchTexto = linha.match(/^- \[x\]\s*(.*)$/);
                  if (matchTexto && matchTexto[1] !== undefined) {
                      respostasUsuario[numeroPergunta] = matchTexto[1].trim();
                      break;
                  }
                }
              }
            });

            let feedback = "## Resultado do Quiz\n\n";
            let todasCorretas = true;

            function sanitizeString(str) {
              str = str.normalize('NFD').replace(/[\u0300-\u036f]/g, ''); // Remove acentos
              str = str.replace(/[\u200B-\u200F\uFEFF\u00A0]/g, '');       // Remove caracteres invisíveis e nbsp
              str = str.replace(/^"(.*)"$/, '$1');                      // Remove aspas externas se houver
              str = str.replace(/\.\s*$/, ''); // Remove ponto final EXATO e espaços no fim
              return str.trim();
            }

            for (const numeroPergunta in respostasCorretas) {
              const respostaCorreta = sanitizeString(respostasCorretas[numeroPergunta]);
              const respostaUsuario = respostasUsuario[numeroPergunta] ? sanitizeString(respostasUsuario[numeroPergunta]) : "";

              if (respostaUsuario === respostaCorreta) {
                feedback += `✅ Pergunta ${numeroPergunta}: Resposta correta!\n`;
              } else {
                feedback += `❌ Pergunta ${numeroPergunta}: Resposta incorreta.\n    Sua resposta: ${respostasUsuario[numeroPergunta] || "Nenhuma resposta selecionada"}\n    Resposta correta: ${respostasCorretas[numeroPergunta]}\n`;
                todasCorretas = false;
              }
            }

            if (todasCorretas) {
              feedback += "\nParabéns! Você acertou todas as perguntas do quiz.";
            } else {
              feedback += "\nPor favor, revise suas respostas e tente novamente.";
            }

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ steps.obter_issue.outputs.issueNumber }},
              body: feedback,
            });
