name: Validar Quiz Histórico em Ordem
on:
  workflow_dispatch:
    inputs: # Esta seção 'inputs' é necessária se você estiver enviando inputs do seu código Java
      content_node_id:
        description: 'The content node ID (Issue ID)'
        required: true
        type: string
      project_id:
        description: 'The project ID'
        required: true
        type: string
      other_project_data:
        description: 'The full json payload of the github project event'
        required: true
        type: string
permissions:
  write-all

jobs:
  validar_quiz:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Obter conteúdo da issue
        id: obter_issue
        uses: actions/github-script@v6
        with:
          script: |
            const issueTitulo = "Desafio Quiz: Histórico em Ordem - Estratégias para a Legibilidade e Eficácia";
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'all',
            });

            const issue = issues.data.find(i => i.title === issueTitulo);

            if (!issue) {
              console.log(`Issue "${issueTitulo}" não encontrada.`);
              return;
            }

            core.setOutput('issueNumber', issue.number);
            return issue.body;

      - name: Validar respostas do quiz
        id: validar_respostas
        uses: actions/github-script@v6
        with:
          script: |
            const issueBody = ${{ steps.obter_issue.outputs.result }};
            if (!issueBody) return;

            const respostasCorretas = {
              "1": "Facilitar a busca, o entendimento e a previsibilidade das alterações ao longo do tempo.",
              "2": "Facilitar a compreensão do que cada entrega realizou e o porquê, tornando o histórico mais fácil de navegar, entender e usar para futuras referências e depuração.",
              "3": "Evitar que trabalho em andamento afete a estabilidade do ramo principal e facilitar a revisão das mudanças antes da integração.",
              "4": "Garantir clareza e consistência no histórico unificado, ajustando as mensagens se necessário para que cada entrega continue representando uma unidade lógica de mudança.",
              "5": "Agrupá-las com outras mudanças relacionadas, a menos que a alteração cosmética seja significativa por si só e mereça uma entrega clara para fins de rastreamento e possível reversão como uma unidade lógica.",
              "6": "Garantir que todos os membros da equipe sigam as mesmas práticas, promovendo consistência, legibilidade e a capacidade de entender o impacto de cada unidade de mudança.",
              "7": "Facilitar a compreensão da evolução do projeto, a colaboração entre a equipe e a manutenção futura, permitindo identificar e reverter unidades lógicas de mudança com clareza.",
              "8": "Manter as entregas do ramo principal focadas em unidades de trabalho coesas e bem descritas, de modo que cada uma represente uma alteração lógica que pode ser revertida como um todo."
            };

            const respostasUsuario = {};
            const perguntas = issueBody.split("# ");

            perguntas.slice(1).forEach(pergunta => {
              const numeroPergunta = pergunta.split(" - ")[0];
              const opcoes = pergunta.split("- [");

              opcoes.slice(1).forEach(opcao => {
                if (opcao.startsWith("x")) {
                  respostasUsuario[numeroPergunta] = opcao.split("] ")[1].trim();
                }
              });
            });

            let feedback = "## Resultado do Quiz\n\n";
            let todasCorretas = true;

            function sanitizeString(str) {
              return str.normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[\u200B-\u200F\uFEFF]/g, '').trim().replace(/^"(.*)"$/, '$1');
            }

            for (const numeroPergunta in respostasCorretas) {
              const respostaCorreta = sanitizeString(respostasCorretas[numeroPergunta]);
              const respostaUsuario = respostasUsuario[numeroPergunta] ? sanitizeString(respostasUsuario[numeroPergunta]) : "";

              if (respostaUsuario === respostaCorreta) {
                feedback += `✅ Pergunta ${numeroPergunta}: Resposta correta!\n`;
              } else {
                feedback += `❌ Pergunta ${numeroPergunta}: Resposta incorreta. Resposta correta: ${respostasCorretas[numeroPergunta]}\n`;
                todasCorretas = false;
              }
            }

            if (todasCorretas) {
              feedback += "\nParabéns! Você acertou todas as perguntas do quiz.";
            } else {
              feedback += "\nPor favor, revise suas respostas e tente novamente.";
            }

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ steps.obter_issue.outputs.issueNumber }},
              body: feedback,
            });
